# Do no use "_" in hostnames. That is forbidden and does not work!!!!!

services:
  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./updated_data/${MONGO_BACKUP_FILE}:/mongo_backup/${MONGO_BACKUP_FILE}
